version: "3"
services:
  wiremock-server:
    image: wiremock/wiremock:latest
    container_name: wiremock-server
    volumes:
      - ./wiremock/api:/home/wiremock
    ports:
      - "8081:8080"

volumes:
  ravendb-data:

networks:
  testes-elastic:
    driver: bridge